### ISSUE TITLE
Enhancement Shaman Script request/issues

### ISSUE THREAD

**Issue by tressym69** [Sidoine/Ovale#26]
Default Script: 7.0.10.1
Talents: Boulderfist, Wind Rush Totem, Lightning Surge Totem, Ancestral Swiftness, Tempest, Crashing Storm, Landslide

Issue 1: The default script is suggesting Stormstrike when there is not enough Maelstrom to cast it AND Boulderfist is off of cooldown but not being suggested.  

Issue 2: (When) Boulderfist is being suggested, correctly, as there is nothing else to cast yet due to Maelstrom needing to be generated, however it is on cooldown without a red cool down timer overlay to show that it is still not available to cast yet.

Thank you again for all of your hard work on this add-on!

**Comment by ShmooDude** [comment]
Not all that familiar with shamans since the patch.  What needs to be updated is the scripts\ovale_shaman_spells.lua file.  With all the changes a lot of that info needs to be updated.  

For those two specific issues:
Stormstrike doesn't currently have its maelstrom cost defined.  To fix it, you'd go to where stormstrike is defined in the file.  Under it you'll find SpellInfo and other similar lines.  In this case I would probably add the maelstrom info to this line:
`	SpellInfo(stormstrike cd=7.5)`
add to it the maelstrom cost (I don't remember the cost off hand, was on my shaman all of 5 minutes, I think 40?) which would look like:
`	SpellInfo(stormstrike cd=7.5 maelstrom=40)`

As far as Boulderfist, that _sounds_ like correct behavior.  Ovale will show whatever spell you should be casting next, even if you don't have the resources/cooldown available yet.  And Since Boulderfist replaces Rockbiter and has a cooldown, you might not be filling every global.

If you want to make a go at fixing more stuff in the file, I can give more specific instructions on what it's looking for and the correct syntax.  I'm pretty sure most of the stormstrike info is wrong at this point, so that's probably true for a lot of it.  It's always easier for someone that knows the class to update it.  Takes a lot of time to update these files so the more people helping the better. :)
