### ISSUE TITLE
Problems with "unknown ID" while importing from SimCraft

### ISSUE THREAD

**Issue by GTmAster** [Sidoine/Ovale#284]
Hi, I'm trying to import SimCraft 720-01 script to Ovale. 
[simcraft_script.txt](https://github.com/Sidoine/Ovale/files/890564/simcraft_script.txt)
Converting process generates some warnings of two types:

> Warning: Unable to find spell 'potion'
> Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell)

And I get this script for Ovale:
[Ovale_script.txt](https://github.com/Sidoine/Ovale/files/890565/Ovale_script.txt)

When I trying to use it, I got a lot of errors from OvaleCompiler of two types:

> Unknown spell with ID beastial_wrath used in SpellCooldown(beastial_wrath)
> Unknown spell with ID potion used in Spell(potion)

And script doesn't work at all. Any idea how to solve this?

**Comment by ShmooDude** [comment]
A workaround is to comment out any lines using potion (there's 2) before importing (put a # in front of it)

`bestial_wrath` is also misspelled (bestial_wrath, not beastial_wrath) and that's why you're getting the error but since the misspelling is in the potion line commenting it out will work for that too.

**Comment by kevindesmet** [comment]
created a ticket for this in simc
https://github.com/simulationcraft/simc/issues/3760
