### ISSUE TITLE
Drood feral script need to be updated

### ISSUE THREAD

**Issue by Linkten** [Sidoine/Ovale#349]
Hi,

First, sorry for my english. With the rework of talents and abilities (33% up global dmg and nerf/up for some abilities) the "cycle dps" from ovale is not good. He don't use savage roar anymore (i think it's cause the talent have been moved) and he ask to use the heal at bad moments.

**Comment by kevindesmet** [comment]
sounds like a job for @ShmooDude :)

**Comment by kurkat** [comment]
I think it's just a result of the talents being moved around.  If you want to implement a temp fix, try this:

Edit the file ovale_druid_spells.lua with notepad or something (in interface\addons\Ovale\Scripts directory of your Warcraft installation directory).

There is a section headed by the comment # Talents

If you look at your talents, the talent numbers are from left to right then down.  Foir instance, the first row of talents (Predator, Blood Scent, and Lunar Inspiration) are 1, 2, and 3 respectively.

For each line where the talent is defined, put it to the new number.  For example, the line;

Define(elunes_guidance_talent 18)

Should be changed to: 

Define(elunes_guidance_talent 21)
, since it moved from the last column of the 6th row to the last column of the seventh row.  I haven't played with it in depth, but I suspect it will solve the problem until the next version.

**Comment by Linkten** [comment]
Well thx for u're answer !

I change that and now it's pretty better. The only problem is Ovale told me to use Savage roar while 10 seconds remain. (it's maybe cause savage roar was during 24seconds for 5 combo points and now it's at 36 seconds for 5 combo points). I search but i just find that 

> Define(savage_roar 52610)
	SpellInfo(savage_roar combo=finisher energy=40 stance=druid_cat_form)
	SpellInfo(savage_roar duration=4 adddurationcp=4)
	SpellRequire(savage_roar energy_percent 50=buff,berserk_cat_buff)
	SpellRequire(savage_roar energy_percent 60=buff,incarnation_king_of_the_jungle_buff)
	SpellInfo(savage_roar unusable=1 talent=!savage_roar_talent)
	SpellAddBuff(savage_roar savage_roar_buff=1)
Define(savage_roar_buff 52610)

That the new Talents code

> # Talents
Define(astral_communion_talent 17)
Define(balance_affinity_talent 7)
Define(blessing_of_the_ancients_talent 18)
Define(blood_scent_talent 2)
Define(bloodtalons_talent 20)
Define(brutal_slash_talent 17)
Define(displacer_beast_talent 5)
Define(elunes_guidance_talent 21)
Define(feral_affinity_talent 8)
# Define(feral_affinity_talent 7) specialization=balance
Define(force_of_nature_talent 1)
Define(fury_of_elune_talent 19)
Define(guardian_affinity_talent 8)
# Define(guardian_affinity_talent 9) specialization=restoration
Define(guardian_of_elune_talent 17)
Define(incarnation_talent 14)
Define(intimidating_roar_talent 5)
Define(jagged_wounds_talent 15)
Define(lunar_inspiration_talent 3)
Define(mass_entanglement_talent 11)
Define(mighty_bash_talent 10)
Define(moment_of_clarity_talent 19)
Define(natures_balance_talent 21)
Define(predator_talent 1)
Define(pulverize_talent 21)
Define(renewal_talent 4)
Define(restoration_affinity_talent 9)
Define(sabertooth_talent 16)
Define(savage_roar_talent 18)
Define(shooting_stars_talent 16)
Define(soul_of_the_forest_talent 13)
Define(starlord_talent 3)
Define(stellar_drift_talent 20)
Define(stellar_flare_talent 15)
Define(survival_of_the_fittest 18)
Define(typhoon_talent 12)
Define(warrior_of_elune_talent 2)
Define(wild_charge_talent 6)
	]]

**Comment by kurkat** [comment]
I think that is as intended by the script.  I don't think it relies on the total duration, but only time remaining...

This line is in the script.  THIS IS NOT THE ONLY PLACE THESE TIMINGS APPEAR, SO IF YOU REALLY WANT TO MAKE A CUSTOM SCRIPT, CHANGE IT THROUGHOUT.  It seems to imply to me that it will request savage roar at 10.5 seconds of buff remaining IF you have the Jagged Wounds Talent (7.2 seconds otherwise) -- not to mention the other conditions.  I assume the logic is that jagged wounds means you need to earn your 5 combo points faster to keep your rip up on average, but I will admit the script is more detailed than my brain can handle.  It probably was written when jagged wounds were a 33% reduction in time rather than the current 20, so I'm sure the simcrafting will necessitate some adjustment to the script.


                if { BuffRemaining(savage_roar_buff) <= 10.5 and Talent(jagged_wounds_talent) or BuffRemaining(savage_roar_buff) <= 7.2 } and ComboPoints() == 5 and { TimeToMaxEnergy() < 1 or BuffPresent(berserk_cat_buff) or BuffPresent(incarnation_king_of_the_jungle_buff) or BuffPresent(elunes_guidance_buff) or SpellCooldown(tigers_fury) < 3 or ArmorSetBonus(T18 4) or BuffPresent(clearcasting_buff) and Energy() > 65 or Talent(soul_of_the_forest_talent) or not target.DebuffPresent(rip_debuff) or target.DebuffRemaining(rake_debuff) < 1.5 and Enemies() < 6 } Spell(savage_roar)

**Comment by Linkten** [comment]
Okey !

Thanks for your answer and thanks for the temp fix !

**Comment by Sidoine** [comment]
shmoodude scripts are now included in the last beta version, please check if they work

**Comment by Linkten** [comment]
With the new beta, ovale with feral druid didn't work. He just tell me to use my legendary item (with shmoodude or other scripts).

**Comment by Linkten** [comment]
Always the same problem with 7.3.1   .2    .3  :(
