### ISSUE TITLE
Balance druid default script empty and simcraft script broken

### ISSUE THREAD

**Issue by Oxxinator** [Sidoine/Ovale#38]
I think Balance druid is broken (on the 7.0 simulationcraft druid balance t18m profile, as the default one is blank and disabled for some reason).   Just suggests moonfire, sunfire, and solar wrath.  It doesn't suggest using starsurge or starfall when near max astral power nor does it suggest using Incarnation: chosen of elune or celestial alignment.  Randomly it will suggest spamming starsurge even when you don't have the astral power to do so.  No interrupt spell suggested as well.

**Comment by ShmooDude** [comment]
Yeah, starsurge doesn't have its astral power set so Ovale think's it's free atm.
#42 fixes it and other stuff that wasn't set correctly.

As far as not suggesting it when near max astral power, are you speced into Fury of Elune?  Because that uses a whole different rotation that pools your resources to get max uptime.  It won't suggest Starsurge at all until you use Fury of Elune.

There also doesn't seem to be any aoe rotation setup yet so until simcraft's action list is updated with one it'll be single target only.

**Comment by kevindesmet** [comment]
Selection of default script is fixed in #49

**Comment by Oxxinator** [comment]
Awesome work guys and thanks.  Apologies, no I was not using Fury of Elune.
