### ISSUE TITLE
Windwalker Monk rotations wrong

### ISSUE THREAD

**Issue by kagekitsune** [Sidoine/Ovale#414]
newest version 7.3.8 does not follow the correct rotation for combo strikes and wants repeating skills (such as blackout kick more then once dropping the combo strikes buff) previous version 7.3.0.3 has the right rotation.

**Comment by Conq1** [comment]
I don't think the script has been changed for a long time. :)
The problem is that PreviousGCDSpell does not seem to be working for Monks. 
I haven't tested it with other classes yet, but at least PreviousGCDSpell(tiger_palm) and PreviousGCDSpell(blackout_kick) seems to always return false.
When I try to debug it is not false I see. Just som #inf response. But as I don't know the inner workings of Ovale I can't be more precise. :)
Hope to see this fixed soon, as it really is a gamebreaker for windwalker.

**Comment by BatManv8v** [comment]
I am still using 7.3.0.3 - not ideal, but at least I have a rotation that does some damage.

Am hoping to see this sorted out soon.
