### ISSUE TITLE
Elemental Shaman rotation problem

### ISSUE THREAD

**Issue by Jaaru** [Sidoine/Ovale#422]
I have been leveling with my Shaman in Pandaria as Enhancement Shaman and the rotation is fine.
But after i tried Elemental the rotation only shows Fire Elemental spell and nothing else.

Whats the problem?

**Comment by Oleandrea** [comment]
I've been lvling since lvl 20. I've used Ovale on other classes at low levels without a problem. But the only spell Ovale tells me to use is the Totem Mastery in both boxes and my Void Tendrils trinket. That's it. Occasionally, it will tell me to use Chain Lightning for groups.   I've tried both options for scripts that are given with the addon, but nothing changes.
