### ISSUE TITLE
Long Cooldown Timer not working

### ISSUE THREAD

**Issue by tommyturb00** [Sidoine/Ovale#45]
The right box where it says "Long Cooldown Abilities" Is not working properly

It cannont detect how long is left on a cooldown.  Whenever i enter combat it jumps from 2m, 6m and in between. And if im not in combat it claims 10m

**Comment by ShmooDude** [comment]
Which one specifically.  It sounds like there's likely some other condition that has to be true before you can use said cooldown.

**Comment by tommyturb00** [comment]
Its on my Assassination Rogue. Vendetta,

**Comment by Vederia** [comment]
Also it show up with correct I have same problem on my MM hunter, for me it is the Trueshot cooldown that basically has the same issue. It gives me correct 3min cd once I used it, but does not count down otherwise. Even when trueshot is available again, it does not show it available again, it actually adds time. So instead of 3min cd it suddenly gives me a 4min cd timer.

**Comment by ShmooDude** [comment]
Oh, thought I replied to this with the answer...  

In terms of Vendetta, Ovale is doing what's correct based on the profile it's using.  `vendetta,if=target.time_to_die<20|buff.maalus.react` The line requires either the target to be dying soon, or the Maalus buff to be up (leg ring).

For MM.  `#trueshot,if=(target.time_to_die>195|target.health.pct<5)|buff.bullseye.stack>15`  Pretty similar, it'll show up until ~3 minutes from the target dying, then it's waiting for the health percent to be <5% or more than 15 bullseye stacks.  But since no one has an artifact yet (let alone that trait) it pretty much defaults to the first two.

**Comment by Vederia** [comment]
ty for reply
