### ISSUE TITLE
Chain lightning not showing keybind

### ISSUE THREAD

**Issue by zzzwhiteboyzzz** [Sidoine/Ovale#450]
All of my abilities are showing their keybind.  The keybind for chain lightning is not showing.  I do not have it on my bars twice.  It is on the 3 key and nowhere else.

**Comment by mwojtkowski** [comment]
Most likely it is caused by wrong spell id.

As I dont have level 110 Shaman on Live, so please check Chain Lightnig spell id in Ovale Action Bar debug.

Go to Interface > Addons > Ovale > Debug > Action Bar you should see Chain Lightning there
it will look like this Keybind: Spell ID SpellName 
so in your case 
3: (spell id here) Chain Lightning 

After you check that:
- go to you warcraft folder Interface\AddOns\Ovale\dist\scripts
- open ovale_shaman_spells.lua and find Define(chain_lightning 421) 
- change 421 to your spell id
- save and reload interface in game with /reload

you should see keybing after that

**Comment by zzzwhiteboyzzz** [comment]
Thank you for the help.  I was able to do what you have posted and it is fixed now.  It had the level 20 version of the spell instead of the upgraded level 70 version.  

Sent from Mail for Windows 10
