### ISSUE TITLE
CALLBACK ERROR???

### ISSUE THREAD

**Issue by Jkeller662** [Sidoine/Ovale#485]
Message: Interface\AddOns\Ovale\dist\GUID.lua:278: Usage: UnitGUID("unit")
Time: Tue Aug 21 17:56:05 2018
Count: 50
Stack: Interface\AddOns\Ovale\dist\GUID.lua:278: Usage: UnitGUID("unit")
(tail call): ?
[C]: ?
Interface\AddOns\Ovale\dist\GUID.lua:278: in function `UnitGUID'
Interface\AddOns\Ovale\dist\Aura.lua:719: in function `ScanAuras'
Interface\AddOns\Ovale\dist\Aura.lua:507: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:145: in function <...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[2]"]:4: in function <[string "safecall Dispatcher[2]"]:4>
[C]: ?
[string "safecall Dispatcher[2]"]:13: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

**Comment by inforcer007** [comment]
Having same prob only happens when I join a group.


------------------------------------------------------------------------------------------------
Message: Interface\AddOns\Ovale\dist\GUID.lua:278: Usage: UnitGUID("unit")
Time: Wed Aug 22 13:44:06 2018
Count: 17
Stack: Interface\AddOns\Ovale\dist\GUID.lua:278: Usage: UnitGUID("unit")
[C]: ?
Interface\AddOns\Ovale\dist\GUID.lua:278: in function `UnitGUID'
Interface\AddOns\Ovale\dist\Aura.lua:719: in function `ScanAuras'
Interface\AddOns\Ovale\dist\Aura.lua:517: in function `?'
...ilo\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119: in function <...ilo\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...ilo\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...ilo\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...ilo\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: in function `SendMessage'
Interface\AddOns\Ovale\dist\GUID.lua:192: in function `?'
...ilo\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119: in function <...ilo\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...ilo\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...ilo\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...ilo\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: in function `Fire'
...rface\AddOns\Ailo\Libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...rface\AddOns\Ailo\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

&

Message: Interface\AddOns\Ovale\dist\GUID.lua:278: Usage: UnitGUID("unit")
Time: Wed Aug 22 13:44:18 2018
Count: 78
Stack: Interface\AddOns\Ovale\dist\GUID.lua:278: Usage: UnitGUID("unit")
[C]: ?
Interface\AddOns\Ovale\dist\GUID.lua:278: in function `UnitGUID'
Interface\AddOns\Ovale\dist\Aura.lua:719: in function `ScanAuras'
Interface\AddOns\Ovale\dist\Aura.lua:517: in function `?'
...ilo\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119: in function <...ilo\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...ilo\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...ilo\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...ilo\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: in function `SendMessage'
Interface\AddOns\Ovale\dist\GUID.lua:161: in function `?'
...ilo\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119: in function <...ilo\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...ilo\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...ilo\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...ilo\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: in function `Fire'
...rface\AddOns\Ailo\Libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...rface\AddOns\Ailo\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

&

Message: Interface\AddOns\Ovale\dist\GUID.lua:278: Usage: UnitGUID("unit")
Time: Wed Aug 22 13:44:17 2018
Count: 190
Stack: Interface\AddOns\Ovale\dist\GUID.lua:278: Usage: UnitGUID("unit")
[C]: ?
Interface\AddOns\Ovale\dist\GUID.lua:278: in function `UnitGUID'
Interface\AddOns\Ovale\dist\Aura.lua:719: in function `ScanAuras'
Interface\AddOns\Ovale\dist\Aura.lua:507: in function `?'
...ilo\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119: in function <...ilo\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...ilo\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...ilo\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...ilo\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: in function `Fire'
...rface\AddOns\Ailo\Libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...rface\AddOns\Ailo\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>
