### ISSUE TITLE
improved_rake error spam

### ISSUE THREAD

**Issue by tehmufifnman** [Sidoine/Ovale#504]
>  [19:59] OvaleCompile: Info: improved_rake is not a parameter keyword in 'rake' spell_aura_list 

This is being spammed in chat

**Comment by alarge** [comment]
To be clear, this is still happening with 8.0.10.

Also, there are two variants, one with 'rake' and one with 'rake_debuff'.

It looks like this problem comes from Shmoo's script.  I was able to stop the spam by commenting out two lines:

SpellDamageBuff(rake improved_rake=2)
SpellDamageBuff(rake improved_rake=2)

I'm not up to date with the latest Ovale syntax, so I don't even know what those lines were supposed to do, but I'm guessing that there was an "improved_rake" definition that got ditched recently, which killed these two lines.

**Comment by tehmufifnman** [comment]
Yes I should have mentioned I am also on 8.0.10, sorry about that!

**Comment by Sidoine** [comment]
Fixed in 8.0.11
