### ISSUE TITLE
Bloodtalons not being saved to Rip

### ISSUE THREAD

**Issue by rwygand** [Sidoine/Ovale#572]
Ovale isn't saving that I've applied (as feral) a Rip with Bloodtalons, so it keep suggesting I overwrite Rip when, in fact, it's a dps loss to do so. Schmoo mentioned this on fluiddruid: 

```Strictly speaking, that's an "Ovale" problem not a "script" problem. Ovale quite often isn't saving Bloodtalons to bleeds properly so it thinks that a bleed is not BT buffed when it actually is (thus, you'd want to overwrite if it wasn't). If someone hasn't already, I'd make a ticket on Ovale's page as I haven't, and probably won't for a while, have time to run it down.

It's actually been a problem for ages, but became a much lower priority in 7.3.5 because we dropped BT in favor of MoC.
```

https://fluiddruid.net/forum/viewtopic.php?f=3&t=5709&start=900#p39126

**Comment by ShmooDude** [comment]
Last time I looked into this issue, I believe it was primarily due to events occurring out of order.  If the buff (Bloodtalons) was removed before the debuff (Rake or Rip) was applied, then it didn't get saved properly.

That may or may not be the case still, might be a while till I can look at it so if someone can solve it in the meantime that's great.

**Comment by InvalidTheory** [comment]
This is happening to me as well.  I noticed that, in Feral, with Sabertooth enabled, the script keeps telling me to reapply Rip instead of using Ferocious Bite.  If you aren't familiar, Sabertooth enables Ferocious Bite to refresh Rip every time its used instead of only refreshing it below 25%.  I copied the script to custom and noticed an error in this line:

`#ferocious_bite,target_if=dot.rip.ticking&dot.rip.remains<3&target.time_to_die>10&(target.health.pct<25alent.sabertooth.enabled)`

it should be

`#ferocious_bite,target_if=dot.rip.ticking&dot.rip.remains<3&target.time_to_die>10&(target.health.pct<25|talent.sabertooth.enabled)`

I looked at the script on GitHub and it's fine, I looked at the script on my local machine and its fine.  Not sure where the error in translation is occurring, but it's happening somewhere.

**Comment by Hemario** [comment]
@InvalidTheory the line you see there is a comment, the line below is what is actually read and parsed by Ovale. Ovale parses the line fine. I think what you're seeing it's just a display error in your text editor.

`if target.DebuffPresent(rip_debuff) and target.DebuffRemaining(rip_debuff) < 3 and target.TimeToDie() > 10 and { target.HealthPercent() < 25 or Talent(sabertooth_talent) } Spell(ferocious_bite)`

**Comment by InvalidTheory** [comment]
Yeah, still a little strange that this line changes...I tried it again and it shows up the same in the Ovale Editor.

Regarding the underlying issue of overwriting Rip, I believe it is because of this line:

`PersistentMultiplier(rip_debuff) > target.DebuffPersistentMultiplier(rip_debuff)`

I took a look at the values and they range between 1, 1.25 (Bloodtalons buffed Rip) and 1.4375 (fully buffed Rip).  For whatever reason, even with a fully buffed Rip, the value will be 1 or 1.25 instead of 1.4375, 

Hope this helps.

**Comment by InvalidTheory** [comment]
I figured out a workaround that should work until we can get the damageMultiplier info corrected in Ovale.  Note that this does not affect the issue of overwriting Rake, only the issue of overwriting Rip.

Rip can only be buffed by 2 things: Bloodtalons & Tiger's Fury.  If you follow Ovale closely, you will see that Bloodtalons is almost always applied before any finisher (Rip, Ferocious Bite, etc).  This means that we should always have a Bloodtalons-buffed Rip, and all we really need to check is if Rip is buffed by Tiger's Fury.

As such, I modified the code below to ONLY do an overwrite if Tiger's Fury is up:

`if not target.DebuffPresent(rip_debuff) or 
target.DebuffRemaining(rip_debuff) <= BaseDuration(rip_debuff) * 0.3 and target.HealthPercent() > 25 and not Talent(sabertooth_talent) or 
target.DebuffRemaining(rip_debuff) <= BaseDuration(rip_debuff) * 0.8 and PersistentMultiplier(rip_debuff) > target.DebuffPersistentMultiplier(rip_debuff) and target.TimeToDie() > 8 **and BuffPresent(tigers_fury_buff)** 
Spell(rip)
unless { not target.DebuffPresent(rip_debuff) or 
target.DebuffRemaining(rip_debuff) <= BaseDuration(rip_debuff) * 0.3 and target.HealthPercent() > 25 and not Talent(sabertooth_talent) or 
target.DebuffRemaining(rip_debuff) <= BaseDuration(rip_debuff) * 0.8 and PersistentMultiplier(rip_debuff) > target.DebuffPersistentMultiplier(rip_debuff) and target.TimeToDie() > 8 **and BuffPresent(tigers_fury_buff)** } and SpellUsable(rip) and SpellCooldown(rip) < TimeToEnergyFor(rip)`
