### ISSUE TITLE
Outlaw Bugs Still ongoing

### ISSUE THREAD

**Issue by inforcer007** [Sidoine/Ovale#573]
### Outlaw bugs still have not been fixed, I guess no ovale users play outlaw?

**1: Blade flurry bug when it activates all the time is still around for single target.** _Raid bosses no adds up._

**2: Blade flurry bug activates at a really long radius prob 100+ yards on AOE sometimes.** _nothing nearby._

**3: SnD bug where it doesn’t see that it has it up and keep suggesting it all the time.**

**4: Simc import errors.**
![ovale](https://user-images.githubusercontent.com/7846165/46515568-f62c6b80-c8a7-11e8-9fee-64d41e71409c.JPG)

**5: Ovale Simc Output into custom script**
![ovale2](https://user-images.githubusercontent.com/7846165/46515569-f6c50200-c8a7-11e8-9117-c74c9d6cb386.JPG)

**Comment by Hemario** [comment]
related to #483

**Comment by Hemario** [comment]
We'll handle the SnD bug in ticket #483 (for which we provided a fix).

I don't understand what you mean by Blade flurry bug. I was checking the script, it should not show in the single target icon ever. I was also not able to reproduce it on a target dummy.

Ovale doesn't have a range check for enemies, this is by design. Blade flurry will thus still be suggested even if the enemies are far away. A checkbox is available to turn on/off the suggestion of blade flurry (middle click once of the icons to see the checkboxes).

**Comment by Hemario** [comment]
Blade flurry has changed since Legion. It is no longer a toggle, but now it's just a buff that will deal 45% of your single target attacks to nearby enemies. It has 2 charges.
However, nothing has changed regarding the conditions for blade flurry. In Legion we checked for `Enemies() >= 2` and in BFA we do the same thing. There is and there never was a range check when calculating how many enemies() we are facing.

The macro you look for:
```/run LibStub:GetLibrary("ovale/Frame").OvaleFrameModule.frame:ToggleCheckBox("opt_blade_flurry")```
or to enable or disable:
```
/run LibStub:GetLibrary("ovale/Frame").OvaleFrameModule.frame:SetCheckBox("opt_blade_flurry", true)
/run LibStub:GetLibrary("ovale/Frame").OvaleFrameModule.frame:SetCheckBox("opt_blade_flurry", false)
```

**Comment by inforcer007** [comment]
Ah I see, no problem.

I tested the run command it works perfectly but now I have another issue.

Updated to latest version and now the default script is broken? Keeps showing stealth icon no matter what I do. It’s fine if I revert to previous version though.

**Comment by Hemario** [comment]
Yes indeed, the bug was reported on Discord as well. A fix is ready, but hasn't been deployed yet.
https://github.com/Sidoine/Ovale/pull/579

**Comment by MtMan1020** [comment]
First, thanks for trying to make the Outlaw perfect, but something has gone terribly wrong. Since the last update all Ovale want me to do is use stealth. When I stealth, it tells me to ambush. I ambush, it tells me to sinister strike, I do and it tells me to stealth. It happens weather Vanish is up or not. So basically it is useless.  It does it on all three scripts so I guess it is a core issue not a script problem.
