### ISSUE TITLE
Monk Windwalker bugs?

### ISSUE THREAD

**Issue by jycouet** [Sidoine/Ovale#596]
Hello, 

I just discover this addon and it looks great!!! 
And would like to help. 

My questions: 
- I see a lot of time my small CD and long CD empty, but it should be always filled by the next ability no?
- Could we make `flying_serpent_kick` optional?

Thank you

**Comment by jycouet** [comment]
Wow @Hemario, nice to see that it was already in the plan to put `flying_serpent_kick` optional 👍 

Just, I see that at the beginning of the file `ovale_monk.ts`, we have: 
```
// THE REST OF THIS FILE IS AUTOMATICALLY GENERATED
// ANY CHANGES MADE BELOW THIS POINT WILL BE LOST
```
If I understand correctly, it's maintly generated by SimC, but it's adapted with optionnal stuff and things like that correct?

**Comment by Hemario** [comment]
@jycouet basically everything is generated by simc. We just enhance the simc code with custom code of ourselves. We try to limit this behavior and try to come as close as possible to what simc introduces.

We understand that having movement abilities into the main rotation can be cumbersome (I know I experience it that way) and that's why we mark certain spells as optional (fel rush is a good example).

Just to clarify, I added the optional part of flying serpent kick after your suggestion. I liked it as soon as I read it and I added it right away. So thank you for that.
