### ISSUE TITLE
Windwalker Monk Script Fault

### ISSUE THREAD

**Issue by Bractoon** [Sidoine/Ovale#84]
Yesterday the WW script was running flawless; I could go zombie mode in a 5-man and do outrageous damage with no effort. Today, the script is running...weird. I didn't really notice there was a problem at all until it kept suggesting Whirling Dragon Punch when Rising Sun Kick hadn't yet been used, and also kept spamming to use Spinning Crane Kick with no chi. The timing seems off too. Sorry if I didn't use the best language for this kinda stuff, not a sim-craft/coder guy, just a grateful user.
Thanks!

**Comment by kevindesmet** [comment]
What was the version you were running yesterday and today?

**Comment by kevindesmet** [comment]
For the Whirling Dragon Punch, it seems that it is an issue with how simulationcraft works.
simc uses the ready() override in order to check whether the spell is ready instead of adding it to the default script

the script just says: `actions+=/whirling_dragon_punch`

while in sc_monk.cpp we can see (line 3318):
`virtual bool ready() override
  {
    // Only usable while Fists of Fury and Rising Sun Kick are on cooldown.
    if ( p() -> cooldown.fists_of_fury -> down() && p() -> cooldown.rising_sun_kick -> down() )
      return monk_melee_attack_t::ready();

    return false;
}`

We will probably need to translate the action from simc into an Ovale if statement where we check the cooldowns of RSK and FoF.

**Comment by Hinalover** [comment]
The thing is that is how Blizzard has coded the ready().  However!!!!! I updated SimC's Action Priority List earlier today with it explicitly saying to use WDP when FoF and RSK. I also did a bit of a revamp to Serenity  APL. So Ovale may need a regeneration of the script.

**Comment by kevindesmet** [comment]
Doesn't that make the implementation of ready() redundant and unnecessary ?

**Comment by kevindesmet** [comment]
Let me confirm that to you. I guess it shouldn't be an issue anymore with the extra conditions in the APL

**Comment by Sidoine** [comment]
Is the issue corrected?
