### ISSUE TITLE
Guardian Druid 7.0.17.0

### ISSUE THREAD

**Issue by Oxxinator** [Sidoine/Ovale#95]
The default script suggests "Moonfire" (Skill) as the main attack if there is no "Galactic Guardian" (Talent) proc and the Moonfire debuff/dot is on the enemy instead of "Swipe" (Skill) which deals more damage.

Second, there appears to be no suggestion of "Thrash" (Skill) when fighting a single target when "Rend and Tear" (Talent) and/or "Blood Frenzy" (Talent) are taken.

Lastly, is there a way to suggest "Mark of Ursol" (Active Mitigation Skill) instead of "Ironfur" (Active Mitigation Skill) when it detects taking more magic damage than physical?

Thanks for all the hard work guys.

**Comment by ShmooDude** [comment]
Both the moonfire and thrash are because of how the guardian simcraft script is written.  I have no idea why it's written that way.

Third, you could, but that doesn't tend to be how magic damage works.  It often comes in big bursts so by the time Ovale has detected that more magic than physical damage is incoming.  I might add it as a checkbox that defaults to off given its limited usefulness.
